=== Cvelth/PaperBlossoms/PaperBlossoms/data/json_schema/clans.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Clans",
    "description": "List of clans",
    "type": "array",
    "items": {
        "description": "Clan",
        "type": "object",
        "properties": {
            "name": {
                "description": "Name of clan",
                "type": "string"
            },
            "reference": {
                "description": "Page reference for clan",
                "type": "object",
                "properties": {
                    "book": {
                        "description": "Book in which reference can be found",
                        "type": "string",
                        "enum": [
                            "CR",
                            "CoS",
                            "Core",
                            "CotFW",
                            "DT",
                            "EE",
                            "FoV",
                            "GMK",
                            "Mantis",
                            "PoW",
                            "SL",
                            "WotW"
                        ]
                    },
                    "page": {
                        "description": "Page on which reference can be found",
                        "type": "integer"
                    }
                },
                "required": [
                    "book",
                    "page"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Page reference for clan",
                        "body": {
                            "book": "$1",
                            "page": "^$2"
                        }
                    }
                ]
            },
            "type": {
                "description": "Greatness of clan",
                "type": "string",
                "enum": [
                    "Great",
                    "Minor",
                    "Other"
                ]
            },
            "ring_increase": {
                "description": "Ring for which the clan grants an increase in rank",
                "type": "string",
                "enum": [
                    "Air",
                    "Earth",
                    "Fire",
                    "Void",
                    "Water"
                ]
            },
            "skill_increase": {
                "description": "Skill for which the clan grants an increase in rank",
                "type": "string",
                "enum": [
                    "Aesthetics",
                    "Command",
                    "Commerce",
                    "Composition",
                    "Courtesy",
                    "Culture",
                    "Design",
                    "Fitness",
                    "Games",
                    "Government",
                    "Labor",
                    "Martial Arts [Melee]",
                    "Martial Arts [Ranged]",
                    "Martial Arts [Unarmed]",
                    "Medicine",
                    "Meditation",
                    "Performance",
                    "Seafaring",
                    "Sentiment",
                    "Skulduggery",
                    "Smithing",
                    "Survival",
                    "Tactics",
                    "Theology"
                ]
            },
            "status": {
                "description": "Baseline status granted by the clan",
                "type": "integer"
            },
            "families": {
                "description": "Families which belong to the clan",
                "type": "array",
                "items": {
                    "description": "Family which belongs to the clan",
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "Name of family",
                            "type": "string"
                        },
                        "reference": {
                            "description": "Page reference for family",
                            "type": "object",
                            "properties": {
                                "book": {
                                    "description": "Book in which reference can be found",
                                    "type": "string",
                                    "enum": [
                                        "CR",
                                        "CoS",
                                        "Core",
                                        "CotFW",
                                        "DT",
                                        "EE",
                                        "FoV",
                                        "GMK",
                                        "Mantis",
                                        "PoW",
                                        "SL",
                                        "WotW"
                                    ]
                                },
                                "page": {
                                    "description": "Page on which reference can be found",
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "book",
                                "page"
                            ],
                            "defaultSnippets": [
                                {
                                    "label": "New Page reference for family",
                                    "body": {
                                        "book": "$1",
                                        "page": "^$2"
                                    }
                                }
                            ]
                        },
                        "ring_increase": {
                            "description": "List of rings for which the family may grant a rank",
                            "type": "array",
                            "items": {
                                "description": "Ring for which family may grant a rank",
                                "type": "string",
                                "enum": [
                                    "Air",
                                    "Earth",
                                    "Fire",
                                    "Void",
                                    "Water"
                                ]
                            }
                        },
                        "skill_increase": {
                            "description": "List of skills for which family grants a rank",
                            "type": "array",
                            "items": {
                                "description": "Skill for which family grants a rank",
                                "type": "string",
                                "enum": [
                                    "Aesthetics",
                                    "Command",
                                    "Commerce",
                                    "Composition",
                                    "Courtesy",
                                    "Culture",
                                    "Design",
                                    "Fitness",
                                    "Games",
                                    "Government",
                                    "Labor",
                                    "Martial Arts [Melee]",
                                    "Martial Arts [Ranged]",
                                    "Martial Arts [Unarmed]",
                                    "Medicine",
                                    "Meditation",
                                    "Performance",
                                    "Seafaring",
                                    "Sentiment",
                                    "Skulduggery",
                                    "Smithing",
                                    "Survival",
                                    "Tactics",
                                    "Theology"
                                ]
                            }
                        },
                        "glory": {
                            "description": "Amount of glory family endows",
                            "type": "integer"
                        },
                        "wealth": {
                            "description": "Amount of wealth family endows",
                            "type": "integer"
                        }
                    },
                    "required": [
                        "name",
                        "reference",
                        "ring_increase",
                        "skill_increase",
                        "glory",
                        "wealth"
                    ],
                    "defaultSnippets": [
                        {
                            "label": "New Family which belongs to the clan",
                            "body": {
                                "name": "$1",
                                "reference": "^$2",
                                "ring_increase": "^[$3]",
                                "skill_increase": "^[$4]",
                                "glory": "^$5",
                                "wealth": "^$6"
                            }
                        }
                    ]
                }
            }
        },
        "required": [
            "name",
            "reference",
            "type",
            "ring_increase",
            "skill_increase",
            "status",
            "families"
        ],
        "defaultSnippets": [
            {
                "label": "New Clan",
                "body": {
                    "name": "$1",
                    "reference": "^$2",
                    "type": "$3",
                    "ring_increase": "$4",
                    "skill_increase": "$5",
                    "status": "^$6",
                    "families": "^[$7]"
                }
            }
        ]
    }
}

=== Cvelth/PaperBlossoms/PaperBlossoms/data/json/clans.json
[
    {
        "name": "Crab",
        "reference": {
            "book": "Core",
            "page": 42
        },
        "type": "Great",
        "ring_increase": "Earth",
        "skill_increase": "Fitness",
        "status": 30,
        "families": [
            {
                "name": "Hida",
                "reference": {
                    "book": "Core",
                    "page": 49
                },
                "ring_increase": ["Earth", "Fire"],
                "skill_increase": ["Command", "Tactics"],
                "glory": 44,
                "wealth": 4
            },
            {
                "name": "Hiruma",
                "reference": {
                    "book": "Core",
                    "page": 49
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Skulduggery", "Survival"],
                "glory": 39,
                "wealth": 3
            },
            {
                "name": "Kaiu",
                "reference": {
                    "book": "Core",
                    "page": 49
                },
                "ring_increase": ["Earth", "Fire"],
                "skill_increase": ["Smithing", "Labor"],
                "glory": 40,
                "wealth": 5
            },
            {
                "name": "Kuni",
                "reference": {
                    "book": "Core",
                    "page": 49
                },
                "ring_increase": ["Earth", "Void"],
                "skill_increase": ["Medicine", "Theology"],
                "glory": 40,
                "wealth": 4
            },
            {
                "name": "Yasuki",
                "reference": {
                    "book": "Core",
                    "page": 49
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Commerce", "Design"],
                "glory": 39,
                "wealth": 10
            }
        ]
    },
    {
        "name": "Crane",
        "reference": {
            "book": "Core",
            "page": 43
        },
        "type": "Great",
        "ring_increase": "Air",
        "skill_increase": "Culture",
        "status": 35,
        "families": [
            {
                "name": "Asahina",
                "reference": {
                    "book": "Core",
                    "page": 50
                },
                "ring_increase": ["Water", "Void"],
                "skill_increase": ["Aesthetics", "Theology"],
                "glory": 40,
                "wealth": 6
            },
            {
                "name": "Daidoji",
                "reference": {
                    "book": "Core",
                    "page": 50
                },
                "ring_increase": ["Earth", "Water"],
                "skill_increase": ["Fitness", "Tactics"],
                "glory": 40,
                "wealth": 7
            },
            {
                "name": "Doji",
                "reference": {
                    "book": "Core",
                    "page": 50
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Courtesy", "Design"],
                "glory": 44,
                "wealth": 8
            },
            {
                "name": "Kakita",
                "reference": {
                    "book": "Core",
                    "page": 50
                },
                "ring_increase": ["Air", "Fire"],
                "skill_increase": ["Aesthetics", "Meditation"],
                "glory": 44,
                "wealth": 7
            }
        ]
    },
    {
        "name": "Dragon",
        "reference": {
            "book": "Core",
            "page": 44
        },
        "type": "Great",
        "ring_increase": "Fire",
        "skill_increase": "Meditation",
        "status": 30,
        "families": [
            {
                "name": "Agasha",
                "reference": {
                    "book": "Core",
                    "page": 51
                },
                "ring_increase": ["Fire", "Void"],
                "skill_increase": ["Medicine", "Smithing"],
                "glory": 40,
                "wealth": 4
            },
            {
                "name": "Kitsuki",
                "reference": {
                    "book": "Core",
                    "page": 51
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Government", "Sentiment"],
                "glory": 44,
                "wealth": 6
            },
            {
                "name": "Mirumoto",
                "reference": {
                    "book": "Core",
                    "page": 51
                },
                "ring_increase": ["Earth", "Water"],
                "skill_increase": ["Fitness", "Tactics"],
                "glory": 44,
                "wealth": 5
            },
            {
                "name": "Togashi Order",
                "reference": {
                    "book": "Core",
                    "page": 51
                },
                "ring_increase": ["Earth", "Void"],
                "skill_increase": ["Fitness", "Theology"],
                "glory": 45,
                "wealth": 3
            }
        ]
    },
    {
        "name": "Lion",
        "reference": {
            "book": "Core",
            "page": 45
        },
        "type": "Great",
        "ring_increase": "Water",
        "skill_increase": "Tactics",
        "status": 35,
        "families": [
            {
                "name": "Akodo",
                "reference": {
                    "book": "Core",
                    "page": 52
                },
                "ring_increase": ["Air", "Earth"],
                "skill_increase": ["Command", "Government"],
                "glory": 44,
                "wealth": 5
            },
            {
                "name": "Ikoma",
                "reference": {
                    "book": "Core",
                    "page": 52
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Composition", "Performance"],
                "glory": 40,
                "wealth": 5
            },
            {
                "name": "Kitsu",
                "reference": {
                    "book": "Core",
                    "page": 52
                },
                "ring_increase": ["Void", "Water"],
                "skill_increase": ["Meditation", "Theology"],
                "glory": 40,
                "wealth": 4
            },
            {
                "name": "Matsu",
                "reference": {
                    "book": "Core",
                    "page": 52
                },
                "ring_increase": ["Earth", "Fire"],
                "skill_increase": ["Command", "Fitness"],
                "glory": 44,
                "wealth": 5
            }
        ]
    },
    {
        "name": "Phoenix",
        "reference": {
            "book": "Core",
            "page": 46
        },
        "type": "Great",
        "ring_increase": "Void",
        "skill_increase": "Theology",
        "status": 30,
        "families": [
            {
                "name": "Asako",
                "reference": {
                    "book": "Core",
                    "page": 53
                },
                "ring_increase": ["Air", "Fire"],
                "skill_increase": ["Culture", "Sentiment"],
                "glory": 40,
                "wealth": 5
            },
            {
                "name": "Isawa",
                "reference": {
                    "book": "Core",
                    "page": 53
                },
                "ring_increase": ["Fire", "Void"],
                "skill_increase": ["Meditation", "Theology"],
                "glory": 44,
                "wealth": 5
            },
            {
                "name": "Kaito",
                "reference": {
                    "book": "Core",
                    "page": 53
                },
                "ring_increase": ["Air", "Void"],
                "skill_increase": ["Fitness", "Theology"],
                "glory": 40,
                "wealth": 4
            },
            {
                "name": "Shiba",
                "reference": {
                    "book": "Core",
                    "page": 53
                },
                "ring_increase": ["Earth", "Water"],
                "skill_increase": ["Meditation", "Tactics"],
                "glory": 40,
                "wealth": 5
            }
        ]
    },
    {
        "name": "Scorpion",
        "reference": {
            "book": "Core",
            "page": 47
        },
        "type": "Great",
        "ring_increase": "Air",
        "skill_increase": "Skulduggery",
        "status": 35,
        "families": [
            {
                "name": "Bayushi",
                "reference": {
                    "book": "Core",
                    "page": 54
                },
                "ring_increase": ["Air", "Fire"],
                "skill_increase": ["Courtesy", "Design"],
                "glory": 44,
                "wealth": 8
            },
            {
                "name": "Shosuro",
                "reference": {
                    "book": "Core",
                    "page": 54
                },
                "ring_increase": ["Air", "Water"],
                "skill_increase": ["Courtesy", "Performance"],
                "glory": 40,
                "wealth": 6
            },
            {
                "name": "Soshi",
                "reference": {
                    "book": "Core",
                    "page": 54
                },
                "ring_increase": ["Air", "Void"],
                "skill_increase": ["Design", "Theology"],
                "glory": 40,
                "wealth": 6
            },
